name: unitTestWorkflow # Name of the workflow

on:
  [push]: # Event that triggers the workflow
    branches: [master] # Branches to run the workflow on
  [pull_request]: # Event that triggers the workflow
    branches: [master] # Branches to run the workflow on

jobs:
  build:
    runs-on: ubuntu-latest # The type of machine to run the job on

    steps:
      - uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Setup Python 3.10 # Sets up a Python environment for use in actions by installing a version of Python and adding to PATH
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Version of Python to use
          cache: "pip" # Optional. To use a previously cached Python environment

      - name: Install dependencies # Runs a set of commands using the runners shell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit tests # Runs a set of commands using the runners shell
        run: |
          python -m pytest -m unit
